### ISSUE TITLE
Importing modules from differents paths

### ISSUE THREAD

**Issue by kmezhoud** [xeaser/Cloud-Inventory-Management#7]
Dear @xeaser 
Thanks for sharing this app.
I am trying to run it but I get some issue when importing modules like:

```
from Base.apiWrapper import importApi
ModuleNotFoundError: No module named 'Base'
```
Base is the folder where is the file apiWrapper. 
I tried this [solution](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder) but does not work for me.
Any suggestion is welcome.
Thanks,
Karim

**Comment by xeaser** [comment]
Hey @kmezhoud sorry couldn't respond earlier. The feature is not developed yet. It's pretty barebones.
Busy with other stuff will get back to this in sometime.
